### ISSUE TITLE
How can I apply the clothes mesh to the new pose?

### ISSUE THREAD

**Issue by qwopqwop200** [aymenmir1/pix2surf#36]
We succeeded in pulling out a new clothes mesh. But the new clothes mesh is oriented upside down and doesn't really fit. How do I get this to work?

**Comment by qwopqwop200** [comment]
![im_42](https://user-images.githubusercontent.com/64115820/146507299-e9f20503-f329-4b85-90a5-58e6176a760d.png)

**Comment by Akash-Nair** [comment]
hello @qwopqwop200 
Could you please help me in doing the same.
