### ISSUE TITLE
executing ./prep_data/run.py: compatibility between python2 vs python3

### ISSUE THREAD

**Issue by wangfudong** [aymenmir1/pix2surf#5]
Thank you very much for your wonderful work!

At first, I could successfully run the demo.py  in a virtualenv with python==3.6.9. However, I found that  the ./prep_data/run.py could not be excuted with py3 since the package cPickle used in py2 is not compatible with py3. 

After that, I tried to build a new virtualenv with py2.7 and then ran ./prep_data/run.py, however, it failed since the package psbody-mesh downloaded from https://github.com/MPI-IS/mesh could not be installed with py2.  

There are also some minor issues caused by the differences of relative path and absolute path in py2 and py3.

I'm now trying to rewrite the sub-project 'prep_data' such that it is compatible with py3. Could you please provide more details about it? 

Thank you~

**Comment by melih1996** [comment]
@wangfudong Could you complete the script running in python3
